- name: Apache Install Remotely
  hosts: web
  become: True

  tasks:
  - name: Inastall Apache
    apt:
      name: "apache2"
      state: "present"
  - name: Copy Files
    copy:
      src: index.html
      dest: /var/www/html/
  - name: Start service  
    service:
      name: apache2
      state: started
      enabled: True
